version: '2'
services:
  accounts:
    build: ./accounts
    image: gather-flag/accounts
    container_name: gather-flag-accounts
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./accounts:/go/src/github.com/devopsdays/gather-flag/accounts

  rooms:
    build: ./rooms
    image: gather-flag/rooms
    container_name: gather-flag-rooms
    depends_on:
      - db
    links:
      - db
    ports:
      - "8081:8081"
    volumes:
      - ./rooms:/go/src/github.com/devopsdays/gather-flag/rooms

  topics:
    build: ./topics
    image: gather-flag/topics
    container_name: gather-flag-topics
    depends_on:
      - db
    links:
      - db
    ports:
      - "8082:8082"
    volumes:
      - ./topics:/go/src/github.com/devopsdays/gather-flag/topics

  db:
    image: mysql:5.7
    container_name: gather-flag-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: gather-flag
       MYSQL_DATABASE: gather-flag
       MYSQL_USER: gather-flag
       MYSQL_PASSWORD: gather-flag

volumes:
    db_data:
